repos:
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
        args: ["-x", "-e", "SC1091"]  # follow source statements, ignore missing sourced files
        files: \.(sh|bash)$|^bin/|^libexec/
        exclude: \.(py|pl)$|colours-to-rgb|extract_urls|git-ls-revisions|stripcolours|todoist-to-markdown|env\.private\.example\.sh
